<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date April 13, 2014 at 07:54 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDSCGenDate is an internal mark
   $CLDSCGenDate = "1397390059";

/* cldsc_use_new_ordering_of_labels : Display description elements corresponding to others at the end */
$GLOBALS['cldsc_use_new_ordering_of_labels'] = FALSE;



?>