<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/repda_lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date May 28, 2014 at 12:08 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLGRPGenDate is an internal mark
   $CLGRPGenDate = "1401293328";

/* multiGroupAllowed : Allow teachers to subscribe a user in several groups */
$GLOBALS['multiGroupAllowed'] = TRUE;


/* tutorCanBeSimpleMemberOfOthersGroupsAsStudent : A tutor attached to a group can subscribe himself to another group as a simple user. */
$GLOBALS['tutorCanBeSimpleMemberOfOthersGroupsAsStudent'] = FALSE;


/* showTutorsInGroupList : Not implemented, name reserved  for future version of Claroline */
$GLOBALS['showTutorsInGroupList'] = FALSE;


/* clgrp_displayMyGroups : Display "my groups" above group list */
$GLOBALS['clgrp_displayMyGroups'] = TRUE;



?>