<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date April 13, 2014 at 07:54 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLKCACHEGenDate is an internal mark
   $CLKCACHEGenDate = "1397390058";

/* cache_lifeTime : Time to keep a cache as valid */
$GLOBALS['cache_lifeTime'] = 10;


/* cache_automaticCleaningFactor : write n-1 times without check if (others) cached files are or not deprecated */
$GLOBALS['cache_automaticCleaningFactor'] = 40;



?>