<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date April 13, 2014 at 07:54 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLLNPGenDate is an internal mark
   $CLLNPGenDate = "1397390059";

/* maxFilledSpace_for_import : Disk space allowed to import scorm package */
$GLOBALS['maxFilledSpace_for_import'] = 100000000;


/* cllnp_resetByUserAllowed : Set to Yes to allow students to reset their progression in learning pathes */
$GLOBALS['cllnp_resetByUserAllowed'] = FALSE;


/* cllnp_documentDefaultTime : Associate a default time in minute to a document that will be used for learnPath tracking */
$GLOBALS['cllnp_documentDefaultTime'] = 0;


/* cllnp_documentDefaultTimeOnce : Only use the document default time once. Once set no additional time will be added (except with the script) */
$GLOBALS['cllnp_documentDefaultTimeOnce'] = TRUE;


/* cllnp_countTimeSpentOnDocument : Allow a script to count time spent on a document-type module */
$GLOBALS['cllnp_countTimeSpentOnDocument'] = TRUE;


/* cllnp_countTimeIntervalCheck : A time interval (in minute) to define when the script has to check if the module is still active */
$GLOBALS['cllnp_countTimeIntervalCheck'] = 1;


/* cllnp_countTimeOverDefault : Only use the counted time if its value is longer than the default time associated to the document */
$GLOBALS['cllnp_countTimeOverDefault'] = TRUE;



?>