<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date April 13, 2014 at 07:54 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLQWZGenDate is an internal mark
   $CLQWZGenDate = "1397390059";

/* enableExerciseExportQTI : Enable IMS-QTI Export */
$GLOBALS['enableExerciseExportQTI'] = TRUE;


/* exercisesPerPage : Number of exercises per page */
$GLOBALS['exercisesPerPage'] = 25;


/* showAllFeedbacks : If activated, all the feedbacks will be shown to users; if not, only those corresponding to the selected or correct answers will be displayed */
$GLOBALS['showAllFeedbacks'] = FALSE;


/* allow_exercise_event_generation : Automatically insert an event in the calendar at the end date */
$GLOBALS['allow_exercise_event_generation'] = TRUE;



?>