<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by 
		C:
		/wamp
		/www
		/repda_lms.profilequinte.com
		/claroline
		/inc
		/lib
		/config.class.php 
 * Date July 30, 2014 at 12:59 PM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * CAUTION THIS FUNCTION HAS BEEN MODIFIED 
 **/

// $CLWIKIGenDate is an internal mark
   $CLWIKIGenDate = "1406739572";

/* showWikiEditorToolbar : Show wiki syntax toolbar */
$GLOBALS['showWikiEditorToolbar'] = TRUE;


/* forcePreviewBeforeSaving : Force text preview before saving it */
$GLOBALS['forcePreviewBeforeSaving'] = TRUE;



?>